### ISSUE TITLE
clone parler translations -> IntegrityError: Key (language_code, master_id) already exists.

### ISSUE THREAD

**Issue by jedie** [andersinno/django-model-publisher-ai#8]
I get the a IntegrityError like:
```
duplicate key value violates unique constraint "news_news_translation_language_code_37dcef35ba6d4d72_uniq"
DETAIL:  Key (language_code, master_id)=(de, 43) already exists.
```

while "publish" action. Code point is here:

```
File "django-model-publisher-ai/publisher/models.py" in publish
  122.         self.clone_translations(draft_obj, publish_obj)
File "django-model-publisher-ai/publisher/models.py" in clone_translations
  216.                 translation.save()
```

Any idea?

**Comment by jedie** [comment]
Ah! It's related to `aldryn_translation_tools.models.TranslatedAutoSlugifyMixin` !

The error comes if `TranslatedAutoSlugifyMixin` is before `PublisherModel` ...

Working order seems to be:
```
class MyModel(TranslatableModelMixin, PublisherModel, TranslatedAutoSlugifyMixin):
```

**Comment by JsseL** [comment]
Sounds like you got it fixed? Closing.

**Comment by jedie** [comment]
Yes. I also working on a `PublisherParlerManager()` and `PublisherParlerModel()` for easier usage...

**Comment by jedie** [comment]
Hm. No it's not fixed :(

The slug will not set correctly if `TranslatedAutoSlugifyMixin` after `PublisherModel` ...

Any idea?
